---
- name: Do prerequisite job for ELK
  hosts: all
  roles: 
    - common
  tasks: 
    - include: roles/common/tasks/main.yml
      tags: pre-elk

- name: Install Elasticsearch for all nodes
  hosts: all
  roles: 
    - elasticsearch
  tasks: 
    - include: roles/elasticsearch/tasks/install.yml
      tags: install-es

- name: Config Elasticsearch for data nodes
  hosts: es_data
  roles: 
    - elasticsearch
  tasks:
    - include: roles/elasticsearch/tasks/config.yml
      tags: config-es

- name: Config Elasticsearch for coordinator nodes
  hosts: es_coordinator
  roles: 
    - elasticsearch
  tasks:
    - block:
        - include: roles/elasticsearch/tasks/config.yml
        - include: roles/elasticsearch/tasks/config_coordinator.yml
      tags: config-coordinator

- name: Start Elasticsearch for all nodes
  hosts: all
  roles: 
    - elasticsearch
  tasks:
    - include: roles/elasticsearch/tasks/start.yml
      tags: start-es

- name: Stop Elasticsearch for all nodes
  hosts: all
  roles: 
    - elasticsearch
  tasks:
    - include: roles/elasticsearch/tasks/stop.yml
      tags: stop-es

- name: Install Kibana for one node
  hosts: kibana
  roles: 
    - kibana
  tasks:
    - include: roles/kibana/tasks/install.yml
      tags: install-kibana
 
- name: Config Kibana for one node
  hosts: kibana
  roles:
    - kibana
  tasks:
    - include: roles/kibana/tasks/config.yml
      tags: config-kibana

- name: Stop Kibana for one node
  hosts: kibana
  roles:
    - kibana
  tasks:
    - include: roles/kibana/tasks/stop.yml
      tags: stop-kibana

- name: Install plugins for Elasticsearch on each node
  hosts: all
  roles:
    - elasticsearch
  tasks:
    - include: roles/elasticsearch/tasks/plugin.yml
      tags: es-plugin

- name: Install plugins for Kibana on one node
  hosts: kibana
  roles:
    - kibana
  tasks:
    - include: roles/kibana/tasks/plugin.yml
      tags: kibana-plugin

