---
- name: Chown files under /usr/share/kibana
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    recurse: yes
  with_items:
    - "{{ kibana_home }}" 

- name: Install plugins for Kibana
  command: "bin/kibana-plugin install {{ item }}"
  become: true
  become_user: "{{ kibana_user }}"
  become_method: sudo
  args:
    chdir: "{{ kibana_home }}"
  with_items: 
    - "{{ kibana_plugin}}"

