---
- name: Add new configs in elasticsearch.yml
  lineinfile:
    dest: "{{ es_conf_dir }}/elasticsearch.yml"
    line: "{{ item }}"
  with_items:
    - "node.master: false"
    - "node.data: false"
    - "node.ingest: false"

